# Generated by Django 3.1.4 on 2020-12-02 16:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='project_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foraged_material', models.CharField(choices=[('Mushroom', 'Mushroom'), ('Shell Foods', 'Shell Foods'), ('Crop', 'Crop'), ('Material', 'Material')], max_length=255)),
                ('short_comment', models.TextField(default=datetime.datetime(2020, 12, 2, 11, 25, 55, 831494), help_text='You may type a 112 char short description of your find or leave the current date and time.', max_length=112)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('count', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('count_type', models.CharField(blank=True, choices=[('ton', 'ton'), ('lbs', 'lbs'), ('oz', 'oz'), ('g', 'g'), ('kg', 'kg'), ('tons', 'tons'), ('whole', 'whole'), ('dozen', 'dozen')], max_length=56)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='forages.projects')),
            ],
        ),
    ]
