# Generated by Django 3.1.4 on 2020-12-02 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='short_comment',
            field=models.TextField(default=datetime.datetime(2020, 12, 2, 11, 31, 42, 264760), help_text='You may type a 112 char short description of your find or leave the current date and time.', max_length=112),
        ),
    ]
