# Generated by Django 3.1.3 on 2020-12-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='entry',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
    ]
