# Generated by Django 3.1.4 on 2020-12-01 21:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='count_type',
            field=models.CharField(choices=[('ton', 'ton'), ('lbs', 'lbs'), ('oz', 'oz'), ('g', 'g'), ('kg', 'kg'), ('tons', 'tons'), ('whole', 'whole')], default=django.utils.timezone.now, max_length=56),
            preserve_default=False,
        ),
    ]
