# Generated by Django 3.1.4 on 2020-12-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forages', '0003_entry_short_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='short_comment',
            field=models.TextField(help_text='You may type a 112 char short description of your find.', max_length=112),
        ),
    ]
