# Generated by Django 3.1.4 on 2020-12-02 15:45

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forages', '0004_auto_20201201_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='likes',
            field=models.ManyToManyField(related_name='project_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entry',
            name='count',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='count_type',
            field=models.CharField(blank=True, choices=[('ton', 'ton'), ('lbs', 'lbs'), ('oz', 'oz'), ('g', 'g'), ('kg', 'kg'), ('tons', 'tons'), ('whole', 'whole'), ('dozen', 'dozen')], max_length=56),
        ),
        migrations.AlterField(
            model_name='entry',
            name='foraged_material',
            field=models.CharField(choices=[('Mushroom', 'Mushroom'), ('Shell Foods', 'Shell Foods'), ('Crop', 'Crop'), ('Material', 'Material')], max_length=255),
        ),
        migrations.AlterField(
            model_name='entry',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='short_comment',
            field=models.TextField(default=datetime.datetime(2020, 12, 2, 10, 45, 4, 568219), help_text='You may type a 112 char short description of your find or leave the current date and time.', max_length=112),
        ),
    ]
