# Generated by Django 3.1.4 on 2020-12-02 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forages', '0005_auto_20201202_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='short_comment',
            field=models.TextField(default=datetime.datetime(2020, 12, 2, 10, 50, 0, 10546), help_text='You may type a 112 char short description of your find or leave the current date and time.', max_length=112),
        ),
    ]
