# Generated by Django 3.1.4 on 2020-12-03 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forages', '0010_auto_20201203_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='count_type',
            new_name='unit',
        ),
        migrations.AlterField(
            model_name='entry',
            name='short_comment',
            field=models.TextField(default=datetime.datetime(2020, 12, 3, 17, 30, 40, 867482), help_text='You may type a 255 char short description of your find or leave the current date and time.', max_length=255),
        ),
    ]
