# Generated by Django 3.1.4 on 2020-12-06 20:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forages', '0015_auto_20201205_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mushrooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mushroom', models.CharField(choices=[('Amanita', 'Amanita'), ('Beech Mushrooms', 'Beech Mushrooms'), ('Black Trumpet Mushrooms', 'Black Trumpet Mushrooms'), ('Brown Cap Boletus', 'Brown Cap Boletus'), ('Button Mushrooms', 'Button Mushrooms'), ('Chanterelle Mushrooms', 'Chanterelle Mushrooms'), ('Cremini Mushrooms', 'Cremini Mushrooms'), ('Enoki Mushrooms', 'Enoki Mushrooms'), ('Green Amanita', 'Green Amanita'), ('Hedgehog Mushrooms', 'Hedgehog Mushrooms'), ('Hen of the Woods Mushrooms', 'Hen of the Woods Mushrooms'), ('Chicken of the Woods', 'Chicken of the Woods'), ('Honey Agaric', 'Honey Agaric'), ('Lactarius Indigo', 'Lactarius Indigo'), ('King Trumpet Mushrooms', 'King Trumpet Mushrooms'), ('Milk Mushrooms', 'Milk Mushrooms'), ('Morel Mushrooms', 'Morel Mushrooms'), ('Oyster Mushrooms', 'Oyster Mushrooms'), ('Porcini Mushrooms', 'Porcini Mushrooms'), ('Portobello Mushrooms', 'Portobello Mushrooms'), ('Russula', 'Russula'), ('Shitake Mushrooms', 'Shitaki Mushrooms'), ('Toadstool', 'Toadstool'), ('Puffball Mushrooms', 'Puffball Mushrooms')], max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='entry',
            name='short_comment',
            field=models.TextField(default=datetime.datetime(2020, 12, 6, 15, 20, 38, 898372), help_text='You may type a 255 char short description of your find or leave the current date and time.', max_length=255),
        ),
        migrations.CreateModel(
            name='MushroomData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated_names', models.CharField(max_length=512)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('mushroom_type', models.CharField(choices=[('Cultivated Mushrooms', 'Cultivated Mushrooms'), ('Wild Mushrooms', 'Wild Mushrooms'), ('Medicinal Mushrooms', 'Medicinal Mushrooms'), ('Psychoactive Mushrooms', 'Psychoactive Mushrooms'), ('Poisonous Mushrooms', 'Poisonous Mushrooms'), ('Useful Mushrooms', 'Useful Mushrooms')], max_length=255)),
                ('classification', models.CharField(choices=[('Saprotrophic Mushrooms', 'Saprotrophic Mushrooms'), ('Mycorrhizal Mushrooms', 'Mycorrhizal Mushrooms'), ('Parasitic Mushrooms', 'Parasitic Mushrooms'), ('Endophytes', 'Endophytes')], max_length=255)),
                ('mushroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mushroom_details', to='forages.mushrooms')),
            ],
        ),
    ]
