# Generated by Django 3.1.4 on 2020-12-07 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forages', '0022_auto_20201206_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='short_comment',
            field=models.TextField(default=datetime.datetime(2020, 12, 6, 23, 28, 21, 708092), help_text='You may type a 512 char short description of your find or leave the current date and time.', max_length=512),
        ),
    ]
