# Generated by Django 3.1.4 on 2020-12-08 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forages', '0029_auto_20201207_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='short_comment',
            field=models.TextField(default=datetime.datetime(2020, 12, 7, 19, 23, 40, 298513), help_text='You may type a 512 char short description of your find or leave the current date and time.', max_length=512),
        ),
    ]
