# Generated by Django 3.1.4 on 2020-12-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201206_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='media/default.jpg', upload_to='profile_pics/'),
        ),
    ]
