# Generated by Django 3.1.4 on 2020-12-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201207_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='media/default.jpg', upload_to='media/profile_pics/'),
        ),
    ]
